language: node_js
env:
  - TARGET=test
node_js:
  - "10"
  - "12"
matrix:
  include:
    - name: Lint
      node_js: "10"
      env:
        - TARGET=lint
    - name: Coverage
      node_js: "10"
      env:
        - TARGET=coverage
script: npm run $TARGET
